### ISSUE TITLE
QIDI slicer 1.1.4 - Error 500 when uploading to printer

### ISSUE THREAD

**Issue by TinkerBarn** [QIDITECH/QIDISlicer#77]
When uploading a sliced project file via LAN/WLAN, error 500 occurred with a long error code. It was difficult for me as a user to recognize the reason for this error.

After a long search, I found the reason. There was already a print file with an identical name '3DBenchy.gcode' on the Q1 Pro printer, I changed the file name in the upload pop-up window to 'My3DBenchy.gcode' and there was no more error message.
The reason may be that the print files supplied in the firmware are read-only.

Request: Please implement an error message "File name already exists" or "This file name must not be used" in the next version.

`HTTP 500: {"error": {"code": 500, "message": "Internal Server Error", "traceback": "Traceback (most recent call last):\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 563, in move\n os.rename(src, real_dst)\n\nOSError: [Errno 18] Invalid cross-device link: '/tmp/moonraker.upload-12667.mru' -> '/home/mks/gcode_files/3DBenchy.gcode'\n\n\nDuring handling of the above exception, another exception occurred:\n\n\nTraceback (most recent call last):\n\n File \"/home/mks/moonraker/moonraker/components/file_manager/file_manager.py\", line 673, in _process_uploaded_file\n upload_info['dest_path'])\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 577, in move\n copy_function(src, real_dst)\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 264, in copy2\n copystat(src, dst, follow_symlinks=follow_symlinks)\n\n File \"/home/mks/moonraker-env/lib/python3.7/shutil.py\", line 205, in copystat\n follow_symlinks=follow)\n\nPermissionError: [Errno 1] Operation not permitted\n\n\nDuring handling of the above `

**Comment by QIDITECH** [comment]
This is not a software problem, this is an error message returned on the firmware.
The issue has been fixed, please try updating the firmware to the latest version.

**Comment by TinkerBarn** [comment]
My QIDI Q1 Pro is already updated to the latest available firmware V4.4.20
So it seems it is not fully fixed in the latest firmware.

**Comment by QIDITECH** [comment]
Thanks for your feedback, we will review the issue and fix it in the next release.
